/**
 * Google Docs API helpers
 * Requires a valid OAuth access token with:
 *   https://www.googleapis.com/auth/documents
 *   https://www.googleapis.com/auth/drive.file
 */

const DOCS_BASE = 'https://docs.googleapis.com/v1/documents'
const DRIVE_BASE = 'https://www.googleapis.com/drive/v3/files'

function authHeaders(token) {
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  }
}

/**
 * Create a new Google Doc with the given title.
 * Returns { id, title, url }
 */
export async function createGoogleDoc(token, title) {
  const res = await fetch(DOCS_BASE, {
    method: 'POST',
    headers: authHeaders(token),
    body: JSON.stringify({ title }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || 'Failed to create Google Doc')
  }
  const doc = await res.json()
  return {
    id: doc.documentId,
    title: doc.title,
    url: `https://docs.google.com/document/d/${doc.documentId}/edit`,
  }
}

/**
 * Fetch metadata for an existing Google Doc by ID.
 * Returns { id, title, url } or throws if not accessible.
 */
export async function getDocMetadata(token, docId) {
  const res = await fetch(`${DRIVE_BASE}/${docId}?fields=id,name`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  if (!res.ok) throw new Error('Google Doc not found or not accessible')
  const file = await res.json()
  return {
    id: file.id,
    title: file.name,
    url: `https://docs.google.com/document/d/${file.id}/edit`,
  }
}

/**
 * Resolve a Google Doc URL or ID string to its document ID.
 * Accepts:
 *   - A full docs.google.com URL
 *   - A bare document ID string
 */
export function parseDocId(input) {
  const trimmed = (input || '').trim()
  const match = trimmed.match(/\/document\/d\/([a-zA-Z0-9_-]+)/)
  if (match) return match[1]
  if (/^[a-zA-Z0-9_-]{20,}$/.test(trimmed)) return trimmed
  return null
}

const REFERENCES_HEADING = 'References'

/**
 * Extract paragraphs with their API-provided startIndex/endIndex.
 */
function extractParagraphs(bodyContent) {
  const paragraphs = []
  for (const el of bodyContent) {
    if (!el.paragraph) continue
    let text = ''
    for (const elem of el.paragraph.elements || []) {
      text += elem.textRun?.content || ''
    }
    paragraphs.push({ text, startIndex: el.startIndex, endIndex: el.endIndex })
  }
  return paragraphs
}

/**
 * Sync citations into a Google Doc.
 *
 * Strategy:
 *   - Finds the paragraph whose text is exactly "References" (case-insensitive).
 *   - Deletes everything from that paragraph to the end of the document.
 *   - Appends a fresh References section in its place.
 *   - Everything above "References" is never touched.
 *   - On first sync (no "References" paragraph), appends to the end of the doc.
 */
export async function syncCitationsToDoc(token, docId, folderName, citations) {
  // ── Fetch current doc ──────────────────────────────────────────────────────
  const fetchRes = await fetch(`${DOCS_BASE}/${docId}`, {
    headers: { Authorization: `Bearer ${token}` },
  })
  if (!fetchRes.ok) throw new Error('Could not access Google Doc')
  const docData = await fetchRes.json()

  const bodyContent = docData.body?.content || []
  const paragraphs = extractParagraphs(bodyContent)

  // Find the "References" heading paragraph
  const refParaIdx = paragraphs.findIndex(
    (p) => p.text.replace(/\n$/, '').trim().toLowerCase() === 'references'
  )

  let docEndIndex = 1
  for (const el of bodyContent) {
    if (el.endIndex) docEndIndex = el.endIndex
  }

  // ── Build the new references section text ─────────────────────────────────
  const now    = new Date().toLocaleString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit' })
  const footer = `Auto-generated by BioScript · Last updated ${now}`
  const body   = citations.length > 0 ? citations.join('\n\n') : 'No papers in this folder yet.'
  // Full block: heading line + blank line + citations + blank line + footer
  const newText = `${REFERENCES_HEADING}\n\n${body}\n\n${footer}\n`

  const requests = []

  if (refParaIdx !== -1) {
    // Delete from the "References" paragraph to the end of doc
    const deleteFrom = paragraphs[refParaIdx].startIndex
    const deleteTo   = docEndIndex - 1  // -1 to preserve the final newline Google Docs requires

    if (deleteTo > deleteFrom) {
      requests.push({
        deleteContentRange: {
          range: { startIndex: deleteFrom, endIndex: deleteTo },
        },
      })
    }
    // Insert fresh references section at the same position
    requests.push({
      insertText: { location: { index: deleteFrom }, text: newText },
    })
    // Style positions relative to deleteFrom
    const headingStart = deleteFrom
    const footerStart  = deleteFrom + REFERENCES_HEADING.length + 1 + 1 + body.length + 1 + 1

    requests.push(
      // Heading: centered, NORMAL_TEXT, no bold, inherits default font
      {
        updateParagraphStyle: {
          range: { startIndex: headingStart, endIndex: headingStart + REFERENCES_HEADING.length },
          paragraphStyle: { namedStyleType: 'NORMAL_TEXT', alignment: 'CENTER' },
          fields: 'namedStyleType,alignment',
        },
      },
      {
        updateTextStyle: {
          range: { startIndex: headingStart, endIndex: headingStart + REFERENCES_HEADING.length },
          textStyle: { bold: false, foregroundColor: { color: { rgbColor: { red: 0, green: 0, blue: 0 } } } },
          fields: 'bold,foregroundColor',
        },
      },
      // Footer: 9pt grey
      {
        updateTextStyle: {
          range: { startIndex: footerStart, endIndex: footerStart + footer.length },
          textStyle: {
            fontSize: { magnitude: 9, unit: 'PT' },
            foregroundColor: { color: { rgbColor: { red: 0.6, green: 0.6, blue: 0.6 } } },
          },
          fields: 'fontSize,foregroundColor',
        },
      },
    )
  } else {
    // No "References" paragraph yet — append to end of doc
    const insertAt = Math.max(docEndIndex - 1, 1)
    requests.push({
      insertText: { location: { index: insertAt }, text: '\n' + newText },
    })
    const headingStart = insertAt + 1  // +1 for the leading \n
    const footerStart  = headingStart + REFERENCES_HEADING.length + 1 + 1 + body.length + 1 + 1

    requests.push(
      {
        updateParagraphStyle: {
          range: { startIndex: headingStart, endIndex: headingStart + REFERENCES_HEADING.length },
          paragraphStyle: { namedStyleType: 'NORMAL_TEXT', alignment: 'CENTER' },
          fields: 'namedStyleType,alignment',
        },
      },
      {
        updateTextStyle: {
          range: { startIndex: headingStart, endIndex: headingStart + REFERENCES_HEADING.length },
          textStyle: { bold: false, foregroundColor: { color: { rgbColor: { red: 0, green: 0, blue: 0 } } } },
          fields: 'bold,foregroundColor',
        },
      },
      {
        updateTextStyle: {
          range: { startIndex: footerStart, endIndex: footerStart + footer.length },
          textStyle: {
            fontSize: { magnitude: 9, unit: 'PT' },
            foregroundColor: { color: { rgbColor: { red: 0.6, green: 0.6, blue: 0.6 } } },
          },
          fields: 'fontSize,foregroundColor',
        },
      },
    )
  }

  const res = await fetch(`${DOCS_BASE}/${docId}:batchUpdate`, {
    method: 'POST',
    headers: authHeaders(token),
    body: JSON.stringify({ requests }),
  })
  if (!res.ok) {
    const err = await res.json().catch(() => ({}))
    throw new Error(err?.error?.message || 'Failed to write bibliography to Google Doc')
  }
  return true
}

/**
 * Convenience alias kept for backwards compatibility.
 */
export async function appendCitationsToDoc(token, docId, folderName, citations) {
  return syncCitationsToDoc(token, docId, folderName, citations)
}
